# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dpu_constr.xdc

# Block Designs: bd/zynq_dpu_system/zynq_dpu_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system || ORIG_REF_NAME==zynq_dpu_system} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_processing_system7_0_0/zynq_dpu_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_dpu_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/zynq_dpu_system_DPUCZDX8G_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0 || ORIG_REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0} -quiet] -quiet

# IP: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/xci/sfm/fp_add/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/xci/sfm/fp_acc/fp_acc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/xci/sfm/fp_div/fp_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/xci/sfm/fp_convert/fp_convert.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/xci/sfm/fp_exp/fp_exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_1/zynq_dpu_system_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_1 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_clk_wiz_0_0/zynq_dpu_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_clk_wiz_0_0 || ORIG_REF_NAME==zynq_dpu_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_0/zynq_dpu_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_2/zynq_dpu_system_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_2 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_axi_interconnect_0_0/zynq_dpu_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_dpu_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_xlconstant_0_0/zynq_dpu_system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_xlconstant_0_0 || ORIG_REF_NAME==zynq_dpu_system_xlconstant_0_0} -quiet] -quiet

# IP: bd/zynq_dpu_system/ip/zynq_dpu_system_auto_us_0/zynq_dpu_system_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_dpu_system_auto_us_0 || ORIG_REF_NAME==zynq_dpu_system_auto_us_0} -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_processing_system7_0_0/zynq_dpu_system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_dpu_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/zynq_dpu_system_DPUCZDX8G_0_0_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0 || ORIG_REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_DPUCZDX8G_0_0/zynq_dpu_system_DPUCZDX8G_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0 || ORIG_REF_NAME==zynq_dpu_system_DPUCZDX8G_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_clk_wiz_0_0/zynq_dpu_system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_clk_wiz_0_0 || ORIG_REF_NAME==zynq_dpu_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_clk_wiz_0_0/zynq_dpu_system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_clk_wiz_0_0 || ORIG_REF_NAME==zynq_dpu_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_clk_wiz_0_0/zynq_dpu_system_clk_wiz_0_0_ooc.xdc

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_0/zynq_dpu_system_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_0/zynq_dpu_system_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_2/zynq_dpu_system_proc_sys_reset_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_2 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_proc_sys_reset_0_2/zynq_dpu_system_proc_sys_reset_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_proc_sys_reset_0_2 || ORIG_REF_NAME==zynq_dpu_system_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_auto_us_0/zynq_dpu_system_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_dpu_system_auto_us_0 || ORIG_REF_NAME==zynq_dpu_system_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/ip/zynq_dpu_system_auto_us_0/zynq_dpu_system_auto_us_0_ooc.xdc

# XDC: /home/gflamis/Documents/zedboard_dpu/vivado_prj/my_zedboard_prj2/my_zedboard_prj2/my_zedboard_prj2.gen/sources_1/bd/zynq_dpu_system/zynq_dpu_system_ooc.xdc
